"""Adiciona campo is_default na tabela company

Revision ID: 1dc2e487c1c8
Revises: 15a333391208
Create Date: 2025-08-21 14:26:39.374161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dc2e487c1c8'
down_revision = '15a333391208'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_default', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('is_default')

    # ### end Alembic commands ###
