"""Atualiza estrutura de orcamentos

Revision ID: 2030f838c427
Revises: 9810b8f5b767
Create Date: 2025-08-25 12:18:17.705652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2030f838c427'
down_revision = '9810b8f5b767'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proposal_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proposal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attention', sa.String(length=200), nullable=True))
        batch_op.drop_column('description')
        batch_op.drop_column('value')
        batch_op.drop_column('billing_unit')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('billing_unit', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('value', sa.NUMERIC(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=False))
        batch_op.drop_column('attention')

    op.drop_table('proposal_item')
    # ### end Alembic commands ###
