"""Adiciona tabelas SaaS multi-tenant

Revision ID: 27694e2bd949
Revises: c34cb9979645
Create Date: 2026-01-22 14:22:52.637591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27694e2bd949'
down_revision = 'c34cb9979645'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('super_admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('nome_completo', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('tenant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subdomain', sa.String(length=50), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('contact_name', sa.String(length=200), nullable=True),
    sa.Column('contact_email', sa.String(length=150), nullable=False),
    sa.Column('contact_phone', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(), nullable=True),
    sa.Column('is_trial', sa.Boolean(), nullable=True),
    sa.Column('max_companies', sa.Integer(), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.Column('max_employees', sa.Integer(), nullable=True),
    sa.Column('storage_limit_gb', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_email')
    )
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_subdomain'), ['subdomain'], unique=True)

    op.create_table('subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('plan_type', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('billing_cycle', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('current_period_start', sa.Date(), nullable=True),
    sa.Column('current_period_end', sa.Date(), nullable=True),
    sa.Column('next_billing_date', sa.Date(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('gateway_customer_id', sa.String(length=100), nullable=True),
    sa.Column('gateway_subscription_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id')
    )
    op.create_table('tenant_feature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('feature_code', sa.String(length=50), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('enabled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'feature_code', name='unique_tenant_feature')
    )
    op.create_table('tenant_invitation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('invited_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['invited_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenant_invitation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_invitation_token'), ['token'], unique=True)

    with op.batch_alter_table('agendamento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_agendamento_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key('fk_agendamento_tenant_id', 'tenant', ['tenant_id'], ['id'])

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_company_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key('fk_company_tenant_id', 'tenant', ['tenant_id'], ['id'])

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_customer_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key('fk_customer_tenant_id', 'tenant', ['tenant_id'], ['id'])

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_document_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key('fk_document_tenant_id', 'tenant', ['tenant_id'], ['id'])

    with op.batch_alter_table('document_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_document_type_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key('fk_document_type_tenant_id', 'tenant', ['tenant_id'], ['id'])

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_employee_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key('fk_employee_tenant_id', 'tenant', ['tenant_id'], ['id'])

    with op.batch_alter_table('epi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_epi_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key('fk_epi_tenant_id', 'tenant', ['tenant_id'], ['id'])

    with op.batch_alter_table('fornecedor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_fornecedor_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key('fk_fornecedor_tenant_id', 'tenant', ['tenant_id'], ['id'])

    with op.batch_alter_table('proposal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_proposal_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key('fk_proposal_tenant_id', 'tenant', ['tenant_id'], ['id'])

    with op.batch_alter_table('servico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_servico_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key('fk_servico_tenant_id', 'tenant', ['tenant_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key('fk_user_tenant_id', 'tenant', ['tenant_id'], ['id'])

    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_vehicle_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key('fk_vehicle_tenant_id', 'tenant', ['tenant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_vehicle_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_user_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('servico', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_servico_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('proposal', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_proposal_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('fornecedor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_fornecedor_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('epi', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_epi_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_employee_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('document_type', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_document_type_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_document_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_customer_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_company_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('agendamento', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_agendamento_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('tenant_invitation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_invitation_token'))

    op.drop_table('tenant_invitation')
    op.drop_table('tenant_feature')
    op.drop_table('subscription')
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_subdomain'))

    op.drop_table('tenant')
    op.drop_table('super_admin')
    # ### end Alembic commands ###
