"""employee documents

Revision ID: 286252d4fd73
Revises: 00de08463069
Create Date: 2025-08-10 19:12:49.218352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '286252d4fd73'
down_revision = '00de08463069'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=80), nullable=True),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.Column('arquivo_path', sa.String(length=300), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employee_document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_document_employee_id'), ['employee_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_document_employee_id'))

    op.drop_table('employee_document')
    # ### end Alembic commands ###
