"""Add permissions to User

Revision ID: 2db0b0ec1248
Revises: 79ac44258070
Create Date: 2026-01-22 17:36:48.560504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2db0b0ec1248'
down_revision = '79ac44258070'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permissions', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('permissions')

    # ### end Alembic commands ###
