"""Add alert_email to Tenant model

Revision ID: 66f27edda493
Revises: 27694e2bd949
Create Date: 2026-01-22 15:39:14.522578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66f27edda493'
down_revision = '27694e2bd949'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alert_email', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.drop_column('alert_email')

    # ### end Alembic commands ###
