"""Adiciona modulo de frota com veiculos e manutencoes

Revision ID: 9df3c3d7073e
Revises: d3bd941c3bbc
Create Date: 2025-09-02 11:17:48.634382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9df3c3d7073e'
down_revision = 'd3bd941c3bbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=True),
    sa.Column('placa', sa.String(length=10), nullable=False),
    sa.Column('renavam', sa.String(length=20), nullable=True),
    sa.Column('venc_licenciamento', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('placa'),
    sa.UniqueConstraint('renavam')
    )
    op.create_table('maintenance_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('km_atual', sa.Integer(), nullable=True),
    sa.Column('tipo_servico', sa.String(length=100), nullable=True),
    sa.Column('local', sa.String(length=200), nullable=True),
    sa.Column('oleo_utilizado', sa.String(length=100), nullable=True),
    sa.Column('responsavel', sa.String(length=150), nullable=True),
    sa.Column('km_proxima_troca', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maintenance_log')
    op.drop_table('vehicle')
    # ### end Alembic commands ###
