"""Adiciona controlo de km e intervalo de oleo para veiculos

Revision ID: c34cb9979645
Revises: fd525efc3f70
Create Date: 2025-09-08 09:08:26.901988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c34cb9979645'
down_revision = 'fd525efc3f70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_km', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('oil_change_km_interval', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_column('oil_change_km_interval')
        batch_op.drop_column('current_km')

    # ### end Alembic commands ###
