"""Adiciona retirada consolidada de EPIs

Revision ID: d3bd941c3bbc
Revises: 2030f838c427
Create Date: 2025-08-25 14:08:44.253683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3bd941c3bbc'
down_revision = '2030f838c427'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
     op.create_table('epi_saida',
     sa.Column('id', sa.Integer(), nullable=False),
     sa.Column('employee_id', sa.Integer(), nullable=True),
     sa.Column('retirado_por', sa.String(length=200), nullable=False),
     sa.Column('data_saida', sa.DateTime(), nullable=True),
     sa.Column('receipt_pdf_path', sa.String(length=300), nullable=True),
     sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
     sa.PrimaryKeyConstraint('id')
     )
    with op.batch_alter_table('movimentacao_epi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saida_id', sa.Integer(), nullable=True))
        batch_op.alter_column('retirado_por',
            existing_type=sa.VARCHAR(length=200),
            nullable=True)
        batch_op.create_foreign_key(
            "fk_movimentacao_epi_saida_id", 'epi_saida',
            ['saida_id'], ['id'])
    # ### end Alembic commands ###
    


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimentacao_epi', schema=None) as batch_op:
        batch_op.drop_constraint('fk_movimentacao_epi_saida_id', type_='foreignkey')
        batch_op.alter_column('retirado_por',
            existing_type=sa.VARCHAR(length=200),
            nullable=False)
        batch_op.drop_column('saida_id')

    op.drop_table('epi_saida')
    # ### end Alembic commands ###