"""funcionario: filho_menor14 + escolaridade

Revision ID: d9a8413e3fdb
Revises: 286252d4fd73
Create Date: 2025-08-11 09:32:14.751655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9a8413e3fdb'
down_revision = '286252d4fd73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filho_menor14', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('escolaridade', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('escolaridade')
        batch_op.drop_column('filho_menor14')

    # ### end Alembic commands ###
