"""Adiciona documentos de veiculos e campos de manutencao

Revision ID: fd525efc3f70
Revises: 9df3c3d7073e
Create Date: 2025-09-02 11:55:22.133726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd525efc3f70'
down_revision = '9df3c3d7073e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=80), nullable=True),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.Column('arquivo_path', sa.String(length=300), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maintenance_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trocou_filtro', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('data_proxima_troca', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_log', schema=None) as batch_op:
        batch_op.drop_column('data_proxima_troca')
        batch_op.drop_column('trocou_filtro')

    op.drop_table('vehicle_document')
    # ### end Alembic commands ###
